### ISSUE TITLE
How to extend model classes?

### ISSUE THREAD

**Issue by faridmovsumov** [ekino/EkinoWordpressBundle#120]
Can I extend model classes?

**Comment by eko** [comment]
Hi @faridmovsumov,

As written in the documentation (see: https://github.com/ekino/EkinoWordpressBundle#override), you can override an entity using the following bundle configuration:

```yaml
ekino_wordpress:
    services:
        post:
            class: MyApp\AppBundle\Entity\Post
```

This way, you can specify your own post entity for instance that will extend the bundle one.

Can you please close this issue if that's ok for you?

Thanks
